# -*- coding: utf-8 -*-
"""Option Strategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-H98I2PVf1-rSSWbRn1fIvWx2NNVyl5x
"""

import matplotlib.pyplot as plt
import numpy as np
CALLprice = {24800:980,24900:905,25000:810,25100:735,25200:670,25300:605,25400:545,25500:486,25600:428,25700:380,25800:327,25900:283,26000:247,26100:213}
PUTprice = {24800:280,24900:310,25000:333,25100:365,25200:411,25300:432,25400:456,25500:510,25600:550,25700:625,25800:685,25900:745,26000:790,26100:850}

def OptionProfit(pos):
  callpos = pos[0]
  putpos = pos[1]
  profit = np.zeros(ST.shape)
  for position in callpos:
    K = position[0]
    N = position[1]
    C = CALLprice[K]
    profit = profit + (np.maximum(ST-K,0)-C)*N
  for position in putpos:
    K = position[0]
    N = position[1]
    P = PUTprice[K]
    profit = profit + (np.maximum(K-ST,0)-P)*N
  return profit

# Scenario 1
ST = np.arange(25300,26000)
pos1_1 = [[[25600,1],[25700,-1]],[]]
pos1_2 = [[[25400,1],[25800,-1]],[]]

p1_1 = OptionProfit(pos1_1)
p1_2 = OptionProfit(pos1_2)
plt.plot(ST,p1_1,'b-',[ST[0],ST[-1]],[0,0],'k--')
plt.plot(ST,p1_2,'y-',[ST[0],ST[-1]],[0,0],'k--')
x_mark = 25650
y1_mark = np.interp(x_mark, ST, p1_1)
y2_mark = np.interp(x_mark, ST, p1_2)
plt.scatter(x_mark, y1_mark, color='red', zorder = 5)
plt.scatter(x_mark, y2_mark, color='red', zorder = 5)
plt.axvline(x=25650, color='black', linestyle='--')
plt.title('Profit')

# Scenario 2
ST = np.arange(25100,25900)
pos2_1 = [[],[[25300,1],[25500,-2],[25700,1]]]
pos2_2 = [[],[[25200,1],[25500,-2],[25800,1]]]
pos2_3 = [[[25500,-1]],[[25500,-1]]]

p2_1 = OptionProfit(pos2_1)
p2_2 = OptionProfit(pos2_2)
p2_3 = OptionProfit(pos2_3)
plt.plot(ST,p2_1,'b-',[ST[0],ST[-1]],[0,0],'k--')
plt.plot(ST,p2_2,'y-',[ST[0],ST[-1]],[0,0],'k--')
plt.plot(ST,p2_3,'g-',[ST[0],ST[-1]],[0,0],'k--')
x_mark = 25500
y1_mark = np.interp(x_mark, ST, p2_1)
y2_mark = np.interp(x_mark, ST, p2_2)
y3_mark = np.interp(x_mark, ST, p2_3)
plt.scatter(x_mark, y1_mark, color='red', zorder = 5)
plt.scatter(x_mark, y2_mark, color='red', zorder = 5)
plt.scatter(x_mark, y3_mark, color='red', zorder = 5)
plt.axvline(x=25500, color='black', linestyle='--')
plt.title('Profit')

# Scenario 3
ST = np.arange(24200,26800)
pos3_1 = [[[25800,1]],[[25200,1]]]
pos3_2 = [[[25700,1]],[[25300,1]]]
pos3_3 = [[[25500,1]],[[25500,1]]]

p3_1 = OptionProfit(pos3_1)
p3_2 = OptionProfit(pos3_2)
p3_3 = OptionProfit(pos3_3)
plt.plot(ST,p3_1,'b-',[ST[0],ST[-1]],[0,0],'k--')
plt.plot(ST,p3_2,'y-',[ST[0],ST[-1]],[0,0],'k--')
plt.plot(ST,p3_3,'g-',[ST[0],ST[-1]],[0,0],'k--')
x_mark = 25500
y1_mark = np.interp(x_mark, ST, p3_1)
y2_mark = np.interp(x_mark, ST, p3_2)
y3_mark = np.interp(x_mark, ST, p3_3)
plt.scatter(x_mark, y1_mark, color='red', zorder = 5)
plt.scatter(x_mark, y2_mark, color='red', zorder = 5)
plt.scatter(x_mark, y3_mark, color='red', zorder = 5)
plt.axvline(x=25500, color='black', linestyle='--')
plt.title('Profit')

# Closer look around 25500
ST = np.arange(25100,25900)
pos3_1 = [[[25800,1]],[[25200,1]]]
pos3_2 = [[[25700,1]],[[25300,1]]]
pos3_3 = [[[25500,1]],[[25500,1]]]

p3_1 = OptionProfit(pos3_1)
p3_2 = OptionProfit(pos3_2)
p3_3 = OptionProfit(pos3_3)
plt.figure()
plt.plot(ST,p3_1,'b-',[ST[0],ST[-1]],[0,0],'k--')
plt.plot(ST,p3_2,'y-',[ST[0],ST[-1]],[0,0],'k--')
plt.plot(ST,p3_3,'g-',[ST[0],ST[-1]],[0,0],'k--')
x_mark = 25500
y1_mark = np.interp(x_mark, ST, p3_1)
y2_mark = np.interp(x_mark, ST, p3_2)
y3_mark = np.interp(x_mark, ST, p3_3)
plt.scatter(x_mark, y1_mark, color='red', zorder = 5)
plt.scatter(x_mark, y2_mark, color='red', zorder = 5)
plt.scatter(x_mark, y3_mark, color='red', zorder = 5)
plt.axvline(x=25500, color='black', linestyle='--')
plt.title('Profit')

# Scenario 4
ST = np.arange(24000,27000)
pos4_1 = [[[24900,-1]],[[24900,1]]]
pos4_2 = [[[25800,-1]],[[25800,1]]]

p4_1 = OptionProfit(pos4_1)
p4_2 = OptionProfit(pos4_2)
plt.plot(ST,p4_1,'b-',[ST[0],ST[-1]],[0,0],'k--')
plt.plot(ST,p4_2,'y-',[ST[0],ST[-1]],[0,0],'k--')
plt.title('Profit')

# Arbitrage
pos4_1 = [[[24900,-1]],[[24900,1]]]
pos4_2 = [[[25800,1]],[[25800,-1]]]
p4_3 = np.zeros(ST.shape)
p4_1 = OptionProfit(pos4_1)
p4_2 = OptionProfit(pos4_2)
p4_3 = p4_1 + p4_2
plt.figure()
plt.plot(ST,p4_1,'b-',[ST[0],ST[-1]],[0,0],'k--')
plt.plot(ST,p4_2,'y-',[ST[0],ST[-1]],[0,0],'k--')
plt.plot(ST,p4_3,'g-',[ST[0],ST[-1]],[0,0],'k--')
plt.title('Profit')
