# -*- coding: utf-8 -*-
"""Binomial Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vi6ZYB4QC6Dg0qSGWhra1NFPB8BiJCoK
"""

import math
import numpy as np

def u_d_p(vol, r, dt):
    u = math.exp(vol * math.sqrt(dt))
    d = 1/math.exp(vol * math.sqrt(dt))
    p = (math.exp(r * dt) - d) / (u - d)
    return u, d, p

vol = 0.3
r = 0.05


month_dt = 1/12
week_dt = 1/52
day_dt = 1/252

# Month
u,d,p = u_d_p(vol,r,month_dt)
print("1-month time steps: ","u: ",u," d: ",d," p: ",p)

# Week
u,d,p = u_d_p(vol,r,week_dt)
print("1-week time steps: ","u: ",u," d: ",d," p: ",p)

# Day
u,d,p = u_d_p(vol,r,day_dt)
print("1-day time steps: ","u: ",u," d: ",d," p: ",p)

## Pricing European Options


import math
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm

def u_d_p(vol, r, dt):
  u = math.exp(vol * math.sqrt(dt))
  d = 1/math.exp(vol * math.sqrt(dt))
  p = (math.exp(r * dt) - d) / (u - d)
  return u, d, p

def Put_option_price(u,d,p,S0,K,step,dt):
  stock_price = np.zeros(step+1)
  put_option_price = np.zeros(step+1)
  for i in range(step+1):
    stock_price[i] = S0 * ( u**(step-i) ) * ( d**(i) )
    put_option_price[i] = max( (K-stock_price[i] ),0)

  for i in range(step-1,-1,-1):
    for j in range(i+1):
      put_option_price[j] = math.exp(-r*dt) * ( p * put_option_price[j] + ( 1-p )*( put_option_price[j+1] ) )

  return put_option_price[0]

def BS(S,K,r,q,sigma,T,OptionType):

  d1=(np.log(S/K)+(r-q+0.5*sigma*sigma)*T)/(sigma*np.sqrt(T))
  d2=(np.log(S/K)+(r-q-0.5*sigma*sigma)*T)/(sigma*np.sqrt(T))

  if (OptionType=='P'):
    BS_Value=K*np.exp(-r*T)*norm.cdf(-d2,0,1)-S*np.exp(-q*T)*norm.cdf(-d1,0,1)
  else:
    BS_Value=S*np.exp(-q*T)*norm.cdf(d1,0,1)-K*np.exp(-r*T)*norm.cdf(d2,0,1)
  return BS_Value



S0 = 50
vol = 0.3
K = 52
T = 2
r = 0.05


print("European put option price:")

# Month
step = 12*T
dt = 1/12
u,d,p = u_d_p(vol,r,dt)
m_put_option_price = Put_option_price(u,d,p,S0,K,step,dt)
print("1-month time steps: ", m_put_option_price)

# Week
step = 52*T
dt = 1/52
u,d,p = u_d_p(vol,r,dt)
w_put_option_price = Put_option_price(u,d,p,S0,K,step,dt)
print("1-week time steps: ", w_put_option_price)

# Day
step = 252*T
dt = 1/252
u,d,p = u_d_p(vol,r,dt)
d_put_option_price = Put_option_price(u,d,p,S0,K,step,dt)
print("1-day time steps: ", d_put_option_price)

# BS

BS_put_price = BS(S0,K,r,0,vol,T,'P')
print("------------")
print("Using Black-Scholes formula:")
print("BS Eueropean put option price: ",BS_put_price)

# Comparison
print("-----------")
print("Difference of binomial price and BS price:")
print("1-month time steps: ",abs( m_put_option_price - BS_put_price ))
print("1-week time steps: ",abs( w_put_option_price - BS_put_price ))
print("1-day time steps: ",abs( d_put_option_price - BS_put_price ))

## Comparison Between BS model and Binomial model

put_option_price = np.zeros(252)

for i in range(252):
  dt = T/(i+1)
  u,d,p = u_d_p(vol,r,dt)
  step = (i+1)
  put_option_price[i] = Put_option_price(u,d,p,S0,K,step,dt)


BS_put_price = BS(S0,K,r,0,vol,T,'P')
## print(BS_put_price)

plt.figure(figsize=(10,6))
plt.plot(np.arange(1,253), put_option_price, linewidth=2, label='Binomial Put Price')
plt.axhline(BS_put_price, color='red', linestyle='--', linewidth=2, label='Black-Scholes Price')
plt.xlabel("Steps")
plt.ylabel("European Put Price")
plt.grid(True, linestyle="--", alpha=0.6)
plt.legend()
plt.show()

## Pricing American options

import math
import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt


def u_d_p(vol, r, dt):
  u = math.exp(vol * math.sqrt(dt))
  d = 1/math.exp(vol * math.sqrt(dt))
  p = (math.exp(r * dt) - d) / (u - d)
  return u, d, p

def American_Put_option_price(u,d,p,S0,K,step,dt):
  stock_price = np.zeros(step+1)
  put_option_price = np.zeros(step+1)
  for i in range(step+1):
    stock_price[i] = S0 * ( u**(step-i) ) * ( d**(i) )
    put_option_price[i] = max( (K-stock_price[i] ),0)

  for i in range(step-1,-1,-1):
    for j in range(i+1):
      stock_price[j] = S0 * ( u**(i-j) ) * ( d**(j) )
      put_option_price[j] = max( math.exp(-r*dt) * ( p * put_option_price[j] + ( 1-p )*( put_option_price[j+1] ) ) , K-stock_price[j] )

  return put_option_price[0]


S0 = 50
vol = 0.3
K = 52
T = 2
r = 0.05

print("American put option prices:")

# Month
step = 12*T
dt = 1/12
u,d,p = u_d_p(vol,r,dt)
put_option_price = American_Put_option_price(u,d,p,S0,K,step,dt)
print("1-month time steps: ", put_option_price)

# Week
step = 52*T
dt = 1/52
u,d,p = u_d_p(vol,r,dt)
put_option_price = American_Put_option_price(u,d,p,S0,K,step,dt)
print("1-week time steps: ", put_option_price)

# Day
step = 252*T
dt = 1/252
u,d,p = u_d_p(vol,r,dt)
put_option_price = American_Put_option_price(u,d,p,S0,K,step,dt)
print("1-day time steps: ", put_option_price)

# Plotting Terminal Price

import numpy as np
import math
import matplotlib.pyplot as plt

def u_d_p(vol, r, dt):
  u = math.exp(vol * math.sqrt(dt))
  d = 1/math.exp(vol * math.sqrt(dt))
  p = (math.exp(r * dt) - d) / (u - d)
  return u, d, p

def terminal_stock_price(u,d,p,S0,step,dt):

   stock_price = np.zeros(step+1)
   for j in range(step+1):
      stock_price[j] = S0 * (u**(step-j)) * (d**j)


   probability = np.zeros(step+1)
   for j in range(step+1):
      probability[j] = math.comb(step, j) * (p**(step-j)) * ((1-p)**j)

   return stock_price, probability


S0 = 50
vol = 0.3
K = 52
T = 2
r = 0.05

# 6 time steps
step = 6
dt = T/6
u,d,p = u_d_p(vol,r,dt)
stock_price,probability = terminal_stock_price(u,d,p,S0,step,dt)

index = np.argsort(stock_price)
x = stock_price[index]
y = probability[index]

plt.figure(figsize=(10,5))
plt.bar(x, y, width=1, align='center', alpha=0.8)
plt.xlabel("Stock Price at T")
plt.ylabel("Probability")
plt.title(f"Probability of terminal stock price (step={step})")
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

# 12 time steps
step = 12
dt = T/12
u,d,p = u_d_p(vol,r,dt)
stock_price,probability = terminal_stock_price(u,d,p,S0,step,dt)

index = np.argsort(stock_price)
x = stock_price[index]
y = probability[index]

plt.figure(figsize=(10,5))
plt.bar(x, y, width=1, align='center', alpha=0.8)
plt.xlabel("Stock Price at T")
plt.ylabel("Probability")
plt.title(f"Probability of terminal stock price (step={step})")
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

# 52 time steps
step = 52
dt = T/52
u,d,p = u_d_p(vol,r,dt)
stock_price,probability = terminal_stock_price(u,d,p,S0,step,dt)

index = np.argsort(stock_price)
x = stock_price[index]
y = probability[index]

plt.figure(figsize=(10,5))
plt.bar(x, y, width=1, align='center', alpha=0.8)
plt.xlabel("Stock Price at T")
plt.ylabel("Probability")
plt.title(f"Probability of terminal stock price (step={step})")
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()